---
- name: "Instalacion y configuracion de serivdor Web"
  hosts: 192.168.0.14
  vars_files:
    vars/default.yml
  
  tasks:
    - name: "Descripcion del ejercicio"
      debug:
        msg: >
          En este ejericicio practicaremos el desarrollo de un playbook desde 0
          para ello, realizaremos varias tareas para levantar un servidor apache

    - name: "Instalacion de httpd"
      yum:
        name: [httpd, httpd-tools]
        state: latest
    
    - name: "Habilitar el firewalld servicio http"
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled
        
    - name: "Habilitar el firewalld servicio https"
      firewalld:                                                                                                                                                                                               
        service: https
        permanent: yes
        immediate: yes
        state: enabled
    
    - name: "Iniciamos el servicio httpd (tambien con el arranque del servidor)"
      service:
        name: httpd
        enabled: yes
        state: restarted
    
    - name: "Deshabilitar el selinux"
      selinux:
        state: disabled
    
    - name: "Creacion del usuario propietario"
      user:
        name: "{{ usuario_propietario }}"
        state: present
    
    - name: "Creacion del directorio para el Host Virtual"
      file:
        path: "/var/www/{{ nombre_virtual_host }}/html"
        owner: "{{ usuario_propietario }}"
        group: "{{ grupo_propietario }}"
        mode: 0765
        recurse: yes
        state: directory

    - name: "Creacion del directorio de logs para el Host Virtual"
      file:                             
        path: /var/www/{{ nombre_virtual_host }}/log                                                                                                                                                                        
        owner: "{{ usuario_propietario }}"                     
        group: "{{ grupo_propietario }}"                     
        mode: 0765                      
        recurse: yes                    
        state: directory

    - name: "Modificar permisos del directorio"
      file:
        path: /var/www
        mode: 0755
        recurse: yes
        state: directory

    - name: "Creacion del index.html"
      file:
        path: /var/www/{{ nombre_virtual_host }}/html/index.html
        mode: 0755
        owner: "{{ usuario_propietario }}"
        group: "{{ grupo_propietario }}"
        state: touch
    
    - name: "Insercion de contenido en el index.html"
      blockinfile:
        path: /var/www/{{ nombre_virtual_host }}/html/index.html 
        block: |
          <html>
          <head>
          <title>Welcome to {{ nombre_virtual_host }}!</title>
          </head>
          <body>
          <h1>Success! The {{ nombre_virtual_host }} virtual host is working!</h1>
          </body>
          </html>
    
    - name: "Creacion del directorio sites-available"
      file:
        path: /etc/httpd/sites-available
        owner: root
        group: root
        mode: 0765
        recurse: yes
        state: directory

    - name: "Creacion del directorio sites-available"
      file:                                                                                                                                                                                                    
        path: /etc/httpd/sites-enabled
        owner: root                                 
        group: root                                 
        mode: 0765                                  
        recurse: yes                                
        state: directory 
    
    - name: "Insertar linea de configuracion"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: "IncludeOptional sites-enabled/*.conf"
        create: yes
    
    - name: "Crear el fichero de configuracion para el Host Virtual"
      file:
        path: /etc/httpd/sites-available/{{ nombre_virtual_host }}.conf
        owner: root
        group: root
        mode: 0755
        state: touch
    
    - name: "Insercion de contenido en el index.html"
      blockinfile:
        path: /etc/httpd/sites-available/{{ nombre_virtual_host }}.conf
        block: |
          <VirtualHost *:{{ puerto_virtual_host }}>
            ServerName www.{{ nombre_virtual_host }}
            ServerAlias {{ nombre_virtual_host }}
            DocumentRoot /var/www/{{ nombre_virtual_host }}/html
            ErrorLog /var/www/{{ nombre_virtual_host }}/log/error.log
            CustomLog /var/www/{{ nombre_virtual_host }}/log/requests.log combined
          </VirtualHost>
    
    - name: Create a symbolic link
      file:
        src: /etc/httpd/sites-available/{{ nombre_virtual_host }}.conf
        dest: /etc/httpd/sites-enabled/{{ nombre_virtual_host }}.conf
        owner: root
        group: root
        force: yes
        state: link
    
    - name: "Reinicio del server"
      reboot:
...