---
- name: "Laboratorio de variables"
  hosts: nodos
  vars:
    paquetes:
      - openssh-server
      - firewalld
      - httpd
      - mariadb-server

    grupos:
      - ctic
      - devops
      - everis
   
  vars_files:
    vars/default.yml

  tasks:
    - name: "Creacion de grupos"
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ grupos }}"

    - name: "Instalacion de servicios"
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ paquetes }}"
     
    - name: "Arrancar los servicios"
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ servicios }}"

    - name: "Creacion de usuario administrador"
      user:
        name: administrador
        groups: "{{ usuarios['administrador']['grupo'] }}"
        generate_ssh_key: "{{ usuarios['administrador']['generar_key'] }}"
        ssh_key_bits: 2048
        ssh_key_file: "{{ usuarios['administrador']['ruta_key'] }}"
        expires: "{{ usuarios['administrador']['expira'] }}"

    - name: "Creacion del usuario everis_prueba"
      user:
        name: everis_prueba
        groups: "{{ usuarios['everis_prueba']['grupo'] }}"
        generate_ssh_key: "{{ usuarios['everis_prueba']['generar_key'] }}"
        uid: "{{ usuarios['everis_prueba']['identificador'] }}"
        expires: "{{ usuarios['everis_prueba']['expira'] }}"

    - name: "Creacion usuario fdoradof"
      user:
        name: fdoradof            
        groups: "{{ usuarios['fdoradof']['grupo'] }}"   
        generate_ssh_key: "{{ usuarios['fdoradof']['generar_key'] }}"
        ssh_key_bits: 2048
        ssh_key_file: "{{ usuarios['fdoradof']['ruta_key'] }}"        
        expires: "{{ usuarios['fdoradof']['expira'] }}"

    - name: "Reiniciar los servicios"
      service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ servicios }}"

    - name: "Reinicio de nodos"
      reboot:

